name: Docker Images Publish

on:
  push:
    branches:
      - master
      paths-ignore:
      - ".gitignore"
      - "*.md"
      - "*.png"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

        name: Prepare
        id: pre
        run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/v}

      - run: |
          cd web
          npm install
          npm run build
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          push: true
          tags: ldxw/next-terminal:latest
          tags: ldxw/next-terminal:${{ steps.pre.outputs.tag }}
      -
        name: Update repo description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ldxw/next-terminal